#- name: DevSecOps local setup
#  hosts: local

- hosts: localhost
  become: true
  roles:
    - { role: cleanup, tags: cleanup }
    - { role: docker, tags: docker }
    - { role: vault, tags: vault }
    - { role: gitlab, tags: gitlab }
    - { role: dojo, tags: dojo }
    - { role: pipeline, tags: pipeline }
    - { role: grafana, tags: grafana }
